### ISSUE TITLE
E-mail template: ubuntu font on client readers / greeting message size

### ISSUE THREAD

**Issue by therealjuan** [ubuntudesign/design-vanilla-framework#298]
While working on moving the Snapcraft e-mail communications to Marketo, I applied the Vanilla template found in [here](https://canonical-webteam.github.io/unified-email-template/examples/product-branded):

![image](https://user-images.githubusercontent.com/8167677/43896711-aad374ec-9bd1-11e8-98e8-d2c6edf43e84.png)

Normally the template looks okay in most mail client readers but gmail or inbox scrap CSS imports. This means no ability to use web fonts on e-mail messages ending up with an oversized size on the greeting message. See example here:

![image](https://user-images.githubusercontent.com/8167677/43896791-ec484786-9bd1-11e8-963f-9d3e83fdb337.png)

### Additional resources

Here you can find the e-mail comms for Marketo in the following [repo](https://github.com/canonical-webteam/snapcraft-email-comms)

**Comment by matthewpaulthomas** [comment]
This doesn’t look like a Vanilla problem. [The template](https://canonical-webteam.github.io/unified-email-template/examples/product-branded) doesn’t seem to use Vanilla, or indeed do any CSS imports other than Google Fonts. So maybe the issue belongs [on `canonical-webteam/unified-email-template`](https://github.com/canonical-webteam/unified-email-template/issues).

That aside, here’s the relevant code:
` <td align="left" style="color:#0E0E0E; font-family: Arial, Sans Serif, Ubuntu; font-size:28px; line-height:31px; font-weight:300; font-style:normal;">`

A couple of oddities here:
- If you have Arial and Ubuntu both installed, Arial will take priority. That seems unintentional.
- As far as I know, there‘s no font called “Sans Serif”. Maybe this was meant to be the generic family “sans-serif”, which maps to Helvetica or Arial or similar. But if so, what’s the point of preferring the ugly “Arial” in particular?

Whether it’s a Vanilla issue or not, maybe we could use `font-size-adjust` to size the intro line relative to the rest of the text. [Gmail allows `font-size-adjust`](https://developers.google.com/gmail/design/reference/supported_css), but I don’t know whether other mailers do.

**Comment by kwm14** [comment]
## Agreed in WG
- In emails you can't embed fonts
- Recommendation we use https://github.com/vanilla-framework/vanilla-framework/blob/e4a14cbd7831186ad74cd8169505891589d6c856/scss/_settings_font.scss#L2

**Comment by deadlight** [comment]
Not a Vanilla issue, as discussed.
