### ISSUE TITLE
Blog post 1: Spacing in Vanilla

### ISSUE THREAD

**Issue by lyubomir-popov** [ubuntudesign/design-vanilla-framework#369]
Overview of how spacing works. Baseline grid, single-direction margin declarations, type scale, information density, etc. Each concept accompanied by a codepen to illustrate.

**Comment by kwm14** [comment]
@lyubomir-popov can you add the link to your blog post here please 😄 so that myself, @spencerbygraves and @deadlight can take a look 👍

**Comment by lyubomir-popov** [comment]
@kwm14 @spencerbygraves @deadlight https://admin.insights.ubuntu.com/wp-admin/post.php?post=88251&action=edit

**Comment by kwm14** [comment]
## Copy review
Great blog post - @lyubomir-popov few suggestions below in **_italic bold_** 😉 loving the code pen examples too 👍 

**Global**
- Always capitalize **_Vanilla_** few instances of lower case in your blog post so worth double checking

**Introduction**
- Vanilla, **_our simple CSS framework behind Canonical's suite of products and services_**

**Vertical rhythm**
- In our case, the base unit size is 0.5rem. Everything – **_from the distance between text baselines to all element heights to all white space between elements, is now a multiple of this base unit_**.

**Type scale**
- **_If_** you wanted to add a new font-size to this scale.

**Units**
- Additionally, we’re currently testing an increase to 1.125rem (from 16px to 18px) on **_the: root_** font-size after a certain breakpoint, which effectively zooms everything by 1.125. 

**Consistent white space in and between elements**﻿
- The baseline grid represents a shift to **_more_** rigorous use of white space, but it only lays the groundwork. Our next **_steps_** were:

- This resulted in **_hundreds_** of tiny adjustments touching every single vanilla element. To give an idea of the overall **_effect_** here’s a before / after comparison of a small subset of elements. 

**Adjustable information density**
- On one hand, it needs to provide a comfortable reading experience on sites like ubuntu.com and snapcraft.io, which benefit from **_the generous_** use of white space.

- All we needed to do was start with the **_dense_** version, and decide how many multiples of the base unit to add to each element.

**Summary**
- I hope this overview **_has given_** insight into how spacing and typography work in **_Vanilla_** 2.0.

**Comment by lyubomir-popov** [comment]
thanks @kwm14 I've updated the copy.

**Comment by spencerbygraves** [comment]
Some small changes agreed with @lyubomir-popov, otherwise looks good 👍

**Comment by lyubomir-popov** [comment]
@spencerbygraves I've done the fixes.

**Comment by lyubomir-popov** [comment]
@matthewpaulthomas I've asked before, buyt the copy has changed completely since then. Would you mind taking a look at my vanilla 2.0 blog post again?

**Comment by kwm14** [comment]
The blog post is now live https://blog.ubuntu.com/2019/03/15/vertical-rhythm-and-spacing-improvements-in-vanilla-framework-2-0 great work @lyubomir-popov
